name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest numpy = ">=1.13" pandas = ">=0.20.3" scipy = ">=1.0.0" xarray = ">=0.10.3" numba = ">=0.40"
      - name: Lint with ruff
        run: |
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          ruff --format=github --target-version=py37 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest
